# Generated by Django 5.2.5 on 2025-08-19 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('area_of_residence', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily')], default='DAILY', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=100)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='himwa_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('ALERT', 'Alert'), ('INFO', 'Info'), ('WARNING', 'Warning')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='himwa_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('MOBILE', 'Mobile'), ('CASH', 'Cash'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='MOBILE', max_length=100)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='himwa_app.bill')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='himwa_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=100)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='himwa_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='biller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='himwa_app.team'),
        ),
    ]
