# Generated by Django 5.2.5 on 2025-08-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himwa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expo_token',
            field=models.CharField(default='qOE08EA5OCq-yL323EhTY8', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748119193/zzy3zwrius3kjrzp4ifc.png', null=True),
        ),
    ]
