# Generated by Django 5.2.5 on 2025-08-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himwa_app', '0003_bill_amount_paid_alter_bill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Chairperson', 'Chairperson'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Accountant', 'Accountant'), ('Water engineer', 'Water engineer'), ('Plumber', 'Plumber')], default='Manager', max_length=100),
        ),
    ]
