# Generated by Django 5.2.5 on 2025-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('himwa_app', '0004_alter_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
